# Generated by Django 5.1.6 on 2025-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("va", models.DecimalField(decimal_places=3, max_digits=10)),
                ("cs", models.DecimalField(decimal_places=3, max_digits=10)),
                ("image", models.ImageField(upload_to="uploads/")),
                (
                    "filtered_image",
                    models.ImageField(blank=True, null=True, upload_to="filtered/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=20)),
            ],
        ),
    ]
