# Generated by Django 5.1.6 on 2025-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="cs",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="uploadedimage",
            name="va",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
