# Generated by Django 5.1.6 on 2025-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0002_alter_uploadedimage_cs_alter_uploadedimage_va"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="camera",
            field=models.CharField(default="na", max_length=20),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="focal_len",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="sensor_h",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="sensor_w",
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10),
            preserve_default=False,
        ),
    ]
